import { StrictMode, useEffect, useState, type FormEvent } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'

type Device = { id:string; hostname:string; platform:string; os_name:string; os_version:string; status:string; agent_version:string; last_seen?:string }
const API = import.meta.env.VITE_API_URL ?? 'http://localhost:8080'
function App() {
  const [devices,setDevices] = useState<Device[]>([]); const [token,setToken] = useState(''); const [error,setError] = useState('')
  const [authenticated,setAuthenticated] = useState(!!localStorage.getItem('token'))
  const load = async () => { const response=await fetch(`${API}/api/v1/devices`,{headers:{Authorization:`Bearer ${localStorage.getItem('token')??''}`}}); if(!response.ok){setError('Sign in to view your organization.');return}; const body=await response.json();setDevices(body.data) }
  useEffect(()=>{load()},[])
  const createToken = async () => { const response=await fetch(`${API}/api/v1/enrollment-tokens`,{method:'POST',headers:{Authorization:`Bearer ${localStorage.getItem('token')??''}`}}); const body=await response.json(); if(response.ok)setToken(body.token);else setError(body.error?.message??'Unable to create token') }
  const online=devices.filter(device=>device.status==='ONLINE').length
  if(!authenticated) return <Login onSuccess={()=>{setAuthenticated(true);load()}} />
  return <main><aside><div className="brand"><span className="mark">C</span><span>CYVERRA <b>NEXUS</b></span></div><nav><a className="active">Overview</a><a>Devices <small>{devices.length}</small></a><a>Monitoring</a><a>Policies</a><a>Automation</a><a>Audit trail</a></nav><div className="tenant"><span className="avatar">CN</span><div><strong>Control room</strong><small>Organization workspace</small></div></div></aside><section className="content"><header><div><p className="eyebrow">OPERATIONS / OVERVIEW</p><h1>Fleet command center</h1><p className="subhead">A clear view of device health, policy drift, and the work waiting for you.</p></div><button onClick={createToken}>＋ Enroll device</button></header>{error&&<div className="notice">{error}</div>}<div className="stats"><Stat label="Total devices" value={devices.length} tone="ink"/><Stat label="Online now" value={online} tone="teal"/><Stat label="Needs attention" value={devices.filter(d=>d.status!=='ONLINE').length} tone="coral"/><Stat label="Policy compliance" value="--" tone="gold"/></div><div className="workspace"><div className="panel fleet"><div className="panel-head"><div><p className="eyebrow">LIVE INVENTORY</p><h2>Managed devices</h2></div><button className="quiet">View all →</button></div>{devices.length===0?<div className="empty"><strong>No devices connected yet</strong><span>Create an enrollment token and run the native agent to bring your first endpoint online.</span>{token&&<code>{token}</code>}<button onClick={createToken}>Generate enrollment token</button></div>:<div className="table"><div className="row heading"><span>Device</span><span>Platform</span><span>Agent</span><span>State</span></div>{devices.map(device=><div className="row" key={device.id}><span><strong>{device.hostname}</strong><small>{device.os_name||device.platform}</small></span><span>{device.platform}</span><span>{device.agent_version}</span><span><i className={`dot ${device.status.toLowerCase()}`}/>{device.status}</span></div>)}</div>}</div><div className="panel activity"><div className="panel-head"><div><p className="eyebrow">SYSTEM PULSE</p><h2>What's happening</h2></div></div><div className="pulse"><div className="pulse-line"><i className="dot online"/><span><strong>Heartbeat service</strong><small>Awaiting connected endpoints</small></span><b>Ready</b></div><div className="pulse-line"><i className="dot gold"/><span><strong>Policy engine</strong><small>Baseline policies not configured</small></span><b>Setup</b></div><div className="pulse-line"><i className="dot coral"/><span><strong>Alert stream</strong><small>No active alerts in this workspace</small></span><b>Quiet</b></div></div></div></div></section></main>
}
function Login({onSuccess}:{onSuccess:()=>void}){const [email,setEmail]=useState('admin@cyverra.local');const [password,setPassword]=useState('');const [error,setError]=useState('');const submit=async(e:FormEvent)=>{e.preventDefault();const response=await fetch(`${API}/api/v1/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const body=await response.json();if(!response.ok){setError(body.error?.message??'Login failed');return}localStorage.setItem('token',body.token);onSuccess()};return <div className="login"><form onSubmit={submit}><span className="mark">C</span><p className="eyebrow">CYVERRA NEXUS</p><h1>Sign in to command</h1><p className="subhead">Access your organization workspace.</p><label>Email<input value={email} onChange={e=>setEmail(e.target.value)} type="email" required/></label><label>Password<input value={password} onChange={e=>setPassword(e.target.value)} type="password" required/></label>{error&&<div className="notice">{error}</div>}<button>Continue →</button></form></div>}
function Stat({label,value,tone}:{label:string,value:string|number,tone:string}){return <div className={`stat ${tone}`}><span>{label}</span><strong>{value}</strong><i/></div>}
createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>)
